table Product
	lineageTag: f4140845-f0e6-49fa-9077-97984ded9714

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c031a530-1e99-4bef-aaac-4a6884433b3f
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SKU
		dataType: string
		lineageTag: 4a9b411a-3185-40d9-8a67-89980cf1144b
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: a53cc582-729f-46f3-8790-e352719e94b7
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Standard Cost'
		dataType: double
		lineageTag: b8867606-4eb7-44b9-8d9d-275048583dcc
		summarizeBy: none
		sourceColumn: Standard Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Color
		dataType: string
		lineageTag: 5d0d93f8-66e1-42d2-b515-02d7d8c9c8ff
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column 'List Price'
		dataType: double
		lineageTag: 7e3bb1bc-ab6d-444a-93ca-0d7445452e2e
		summarizeBy: none
		sourceColumn: List Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Model
		dataType: string
		lineageTag: 276c2f19-406d-4e7a-bc79-65b48fbf6a5e
		summarizeBy: none
		sourceColumn: Model

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: 22c40d7c-8b1e-449a-9d68-3f5bb607ef83
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: ab11996b-ddb1-46d7-8d7e-38bf0ff9cba4
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	hierarchy Products
		lineageTag: 7f02c50c-44f0-4910-a9a3-790e81c80e40

		level Category
			lineageTag: fe114fe1-70c2-463a-b8ef-ef42c2586889
			column: Category

		level Subcategory
			lineageTag: 7cca5e1e-d94d-4103-8f37-c64d87919fec
			column: Subcategory

		level Model
			lineageTag: 298b4a46-038b-4ff4-80b4-9ab511760cc6
			column: Model

		level Product
			lineageTag: a2e1f657-7a40-444e-aa12-c164324924e0
			column: Product

	partition Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\TA25851\Downloads\AdventureWorks Sales.xlsx"), null, true),
				    Product_Table = Source{[Item="Product",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Product_Table,{{"ProductKey", Int64.Type}, {"SKU", type text}, {"Product", type text}, {"Standard Cost", type number}, {"Color", type text}, {"List Price", type number}, {"Model", type text}, {"Subcategory", type text}, {"Category", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

