table Reseller
	lineageTag: f6869db6-d133-4a8f-a06b-e98cc8679e4c

	column ResellerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6c51936b-5c74-4756-9cba-1e9b929dea79
		summarizeBy: none
		sourceColumn: ResellerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Reseller ID'
		dataType: string
		lineageTag: c3e54da7-4e62-44f3-8957-425ad150e148
		summarizeBy: none
		sourceColumn: Reseller ID

		annotation SummarizationSetBy = Automatic

	column 'Business Type'
		dataType: string
		lineageTag: 1dbe6cf4-d2cc-488b-b638-cc9de7b5bc8b
		summarizeBy: none
		sourceColumn: Business Type

		annotation SummarizationSetBy = Automatic

	column Reseller
		dataType: string
		lineageTag: 4a096734-50b5-4458-a303-23c7458eb4ca
		summarizeBy: none
		sourceColumn: Reseller

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: cbefd94f-b03c-463f-87cd-8e73a7aa33a1
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State-Province
		dataType: string
		lineageTag: 20e388b6-1b55-415e-82a5-75e0ca3fd1ad
		summarizeBy: none
		sourceColumn: State-Province

		annotation SummarizationSetBy = Automatic

	column Country-Region
		dataType: string
		lineageTag: 708a72b7-37d9-4feb-98ab-52187d2fef21
		summarizeBy: none
		sourceColumn: Country-Region

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: b8cad537-fa63-40b9-9873-6aa1abe7d793
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	hierarchy Geography
		lineageTag: de23e35c-a884-48b2-bd28-915e12d3ecf6

		level Country-Region
			lineageTag: d3e3d1d4-a0f4-4fb1-b6fd-f9c2d0053bba
			column: Country-Region

		level State-Province
			lineageTag: 0c613663-0d95-4fa9-ab7d-4596afd942d3
			column: State-Province

		level City
			lineageTag: fd62e145-7451-4fad-b706-5a302cb93bc0
			column: City

		level 'Postal Code'
			lineageTag: c2da2df9-dbb4-4624-96a0-fd6ac9624cc5
			column: 'Postal Code'

		level Reseller
			lineageTag: f0f5dc2b-71ad-4e1d-b6e7-c7e269ad3fc7
			column: Reseller

	partition Reseller = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\TA25851\Downloads\AdventureWorks Sales.xlsx"), null, true),
				    Reseller_Table = Source{[Item="Reseller",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Reseller_Table,{{"ResellerKey", Int64.Type}, {"Reseller ID", type text}, {"Business Type", type text}, {"Reseller", type text}, {"City", type text}, {"State-Province", type text}, {"Country-Region", type text}, {"Postal Code", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

